### ISSUE TITLE
PrácticaHilosConsola

### ISSUE THREAD

**Issue by Gregorio012** [SistemasTecTlaxiaco/practica-de-hilos-Gregorio012#3]
[HilosConsola_GregorioOsorioSarmiento.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-Gregorio012/files/8834281/HilosConsola_GregorioOsorioSarmiento.pdf)

**Comment by g00gle2401** [comment]
Calificación: 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado
